# Generated by Django 2.0.9 on 2018-11-06 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20181106_0108'),
        ('perro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Persona'),
        ),
    ]
