# Generated by Django 2.0.9 on 2018-11-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perro', '0016_auto_20181107_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
