# Generated by Django 2.0.9 on 2018-11-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perro', '0017_auto_20181107_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='perro/images/'),
        ),
    ]
