# Generated by Django 2.0.9 on 2018-11-07 23:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perro', '0021_auto_20181107_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='localhost:8000/media/photos'), upload_to=''),
        ),
    ]
