# Generated by Django 2.0.9 on 2018-11-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perro', '0022_auto_20181107_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
