# Generated by Django 2.0.9 on 2018-11-08 00:04

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perro', '0023_auto_20181107_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='persona',
        ),
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
