# Generated by Django 2.0.9 on 2018-11-08 00:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perro', '0024_auto_20181107_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to=''),
        ),
    ]
