# Generated by Django 2.0.9 on 2018-11-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_persona_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
