# Generated by Django 2.1.2 on 2018-11-07 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20181106_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dv',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
