# Generated by Django 2.0.9 on 2018-11-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='persona',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
