# Generated by Django 2.0.9 on 2018-11-07 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0007_auto_20181107_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=8),
        ),
    ]
