# Generated by Django 2.0.9 on 2018-11-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0010_auto_20181107_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopcion',
            name='domicilio',
        ),
    ]
