# Generated by Django 2.0.9 on 2018-11-08 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0011_remove_adopcion_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='correo',
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
    ]
