# Generated by Django 2.0.9 on 2018-11-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_auto_20181107_2011'),
        ('adopcion', '0012_adopcion_correo'),
    ]

    operations = [
    ]
